# Generated by Django 5.0.3 on 2026-03-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('chambres', models.IntegerField()),
                ('salles_de_bain', models.IntegerField()),
                ('image', models.ImageField(upload_to='maisons/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
