# Generated by Django 5.0.3 on 2026-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('prix', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='biens/')),
                ('type_bien', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Propriete',
        ),
    ]
