# Generated by Django 5.0.3 on 2026-04-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bien_delete_propriete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='prix',
        ),
        migrations.AddField(
            model_name='bien',
            name='lieu',
            field=models.CharField(default='Ngor/Almadies', max_length=100),
        ),
        migrations.AlterField(
            model_name='bien',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_bien',
            field=models.CharField(max_length=50),
        ),
    ]
