# Generated by Django 5.0.3 on 2026-04-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_bien_prix_bien_lieu_alter_bien_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='prix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bien',
            name='image',
            field=models.ImageField(upload_to='biens/'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_bien',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
